In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
df=pd.read_excel("C:/Users/User/Downloads/multivariate_data.xlsx")

In [7]:
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [11]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [12]:
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [16]:
x_train

array([[  14.2 ,   42.86, 1031.96,   69.59],
       [  28.79,   68.51, 1013.02,   62.84],
       [  14.55,   41.7 , 1018.58,   80.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [26]:
print(reg.intercept_)

451.9495039203386


In [27]:
print(reg.coef_)

[-1.96950789 -0.23767112  0.06473976 -0.15782574]


In [29]:
y_pred=reg.predict(x_test)
y_pred

array([431.43458966, 458.57522935, 462.76604909, ..., 473.74893817,
       475.43985731, 442.01760971])

In [30]:
ndf=pd.DataFrame({'actual':y_test,'predicted':y_pred})
ndf

actual   predicted
0     431.23  431.434590
1     460.01  458.575229
2     461.14  462.766049
3     445.90  448.606498
4     451.29  457.876052
...      ...         ...
2387  434.38  442.769494
2388  451.97  454.897695
2389  468.90  473.748938
2390  473.90  475.439857
2391  437.07  442.017610

[2392 rows x 2 columns]

In [31]:
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [32]:
from sklearn import metrics

In [33]:
df.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [34]:
print("mean absolute error=",metrics.mean_absolute_error(y_test,y_pred))
print("mean square error=",metrics.mean_squared_error(y_test,y_pred))
print("root mean squared error =",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

mean absolute error= 3.5614824152962083
mean square error= 19.832157671694773
root mean squared error = 4.453331075913262
